name: CrosWuft Blog Workflow Demo
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install
          npm run build


      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: dist
          TARGET_FOLDER: .
          BUILD_SCRIPT: npm run build
          BUILD_DIR: dist
          BUILD_WAIT: 5
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          COMMIT_EMAIL: ${{ github.event.head_commit.author.email }}
          COMMIT_BRANCH: ${{ github.ref }}
          COMMIT_SHA: ${{ github.sha }}